"""
Django settings for mysite project.
Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# =========================
# BASE DIR
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# CARGAR VARIABLES DE ENTORNO
# =========================
# .env -> para Docker
# .env.local -> para entorno local de desarrollo
env_file = BASE_DIR / '.env'
env_local_file = BASE_DIR / '.env.local'

if env_file.exists():
    load_dotenv(dotenv_path=env_file)

if env_local_file.exists():
    load_dotenv(dotenv_path=env_local_file, override=True)  # override asegura que las locales prevalezcan

# =========================
# SEGURIDAD
# =========================
SECRET_KEY = 'django-insecure-b&0_59zm+zw5^^#y)&m&p)mc1_7e0@l9(+!p%^vye6+&^c1xi&'
DEBUG = True
ALLOWED_HOSTS = []

# =========================
# APPS
# =========================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'myapp',
    'tailwind',
    'django_browser_reload',
    'corsheaders',
]

# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',  # Auto-reload CSS
]

ROOT_URLCONF = 'mysite.urls'

# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'myapp' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# =========================
# DATABASES
# =========================
# Lee variables de entorno para que funcione tanto en Docker como local
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'reservacionesdb'),
        'USER': os.getenv('DB_USER', 'nuca'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'nuca123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),  # 'db' en Docker, 'localhost' local
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}

# =========================
# PASSWORD VALIDATION
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =========================
# INTERNACIONALIZACIÓN
# =========================
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =========================
# ARCHIVOS ESTÁTICOS Y MEDIA
# =========================
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'myapp/theme/static',
    BASE_DIR / 'myapp/static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =========================
# LOGIN/LOGOUT
# =========================
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# =========================
# TAILWIND
# =========================
TAILWIND_APP_NAME = 'myapp.theme'
NPM_BIN_PATH = "T:/npm.cmd"  # Donde está npm en tu PC

# =========================
# CORS
# =========================
CORS_ALLOW_ALL_ORIGINS = True

# =========================
# REST Framework
# =========================
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# =========================
# SESIONES
# =========================
SESSION_COOKIE_AGE = 1209600  # 2 semanas
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# =========================
# IPs internas para django-browser-reload
# =========================
INTERNAL_IPS = [
    "127.0.0.1",
]
