# Generated by Django 5.2.1 on 2025-11-18 02:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_salon', models.CharField(choices=[('reuniones', 'Reuniones'), ('expos', 'Expos'), ('fiestas', 'Fiestas')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='salones/')),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('reuniones', 'Reuniones'), ('expos', 'Expos'), ('fiestas', 'Fiestas')], default='reuniones', max_length=20)),
                ('ciudad', models.CharField(default='CDMX', max_length=100)),
                ('servicios_extras', models.ManyToManyField(blank=True, to='myapp.servicioextra')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salon')),
            ],
            options={
                'unique_together': {('usuario', 'salon')},
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('pagada', models.BooleanField(default=False)),
                ('precio_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.salon')),
                ('servicios_extra', models.ManyToManyField(blank=True, to='myapp.servicioextra')),
            ],
            options={
                'unique_together': {('salon', 'fecha_reserva')},
            },
        ),
    ]
