# Generated by Django 5.2.1 on 2025-11-18 04:27

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='created_at',
            field=models.DateTimeField(default=myapp.models.default_created_at),
        ),
    ]
