# Generated by Django 5.2.1 on 2025-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_salon_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioextra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
    ]
